# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: 2010-09-09
Description: |
  Resources needed for custodian hub account
  {"framework": "servicecatalog-products", "role": "product", "product-set": "cloud-custodian", "product": "hub", "version": "v4"}

Parameters:
  AWSOrgID:
    Type: String
    Description: Organization Id for the current AWS Organization
    AllowedPattern: o-[a-z0-9]{10,32}

Resources:
  EventBusPolicy:
    Type: AWS::Events::EventBusPolicy
    Description: Grants perms for the given org to putevents
    Properties:
      Action: events:PutEvents
      Principal: "*"
      StatementId: OrganizationAccounts
      Condition:
        Type: "StringEquals"
        Key: "aws:PrincipalOrgID"
        Value: !Ref AWSOrgID
